// GENERATED by scripts/generate-sellable-slugs.ts — do not edit by hand.
// Run: npm run generate:sellable-slugs
//
// Client-safe list of sellable product slugs. CartProvider uses it to purge a
// saved bag line for a product that is no longer sold.
export const SELLABLE_PRODUCT_SLUGS: ReadonlySet<string> = new Set([
  "black-sheep-tee",
  "dont-lick-the-boot-tee",
  "enemy-of-the-state-hoodie",
  "no-kings-tee",
  "read-banned-books-tee",
  "sheep-min-hoodie",
]);
