/**
 * Emit the set of currently sellable product slugs for the CLIENT bundle.
 *
 * CartProvider runs in the browser and must drop a saved bag line that points at
 * something no longer sold — otherwise a bag saved before the reset renders a
 * retired product with a dead PDP link. It cannot call loadProducts(): importing
 * the manifest into the client bundle would ship ~800 KB of catalog to every
 * visitor.
 *
 * So the slugs are generated here and committed. Regenerate whenever the
 * sellable set changes; validate-apliiq-map fails if the file drifts.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { loadProducts } from "@/lib/data/products";
import { checkVariantPurchasable } from "@/lib/data/purchasable";
import { isSellableProvider } from "@/lib/commerce/catalog-policy";

export function computeSellableSlugs(): string[] {
  return loadProducts()
    .filter((p) => p.variants.some((v) => isSellableProvider(v.fulfillmentProvider) && checkVariantPurchasable(p, v).ok))
    .map((p) => p.slug)
    .sort();
}

const OUT = resolve(process.cwd(), "lib/commerce/sellable-slugs.generated.ts");

export function renderModule(slugs: string[]): string {
  return `// GENERATED by scripts/generate-sellable-slugs.ts — do not edit by hand.\n`
    + `// Run: npm run generate:sellable-slugs\n`
    + `//\n`
    + `// Client-safe list of sellable product slugs. CartProvider uses it to purge a\n`
    + `// saved bag line for a product that is no longer sold.\n`
    + `export const SELLABLE_PRODUCT_SLUGS: ReadonlySet<string> = new Set([\n`
    + slugs.map((s) => `  ${JSON.stringify(s)},`).join("\n")
    + `\n]);\n`;
}

if (process.argv[1] && process.argv[1].endsWith("generate-sellable-slugs.ts")) {
  const slugs = computeSellableSlugs();
  writeFileSync(OUT, renderModule(slugs));
  console.log(`✓ generate-sellable-slugs: ${slugs.length} slug(s) -> lib/commerce/sellable-slugs.generated.ts`);
}
