"use client";
import { useEffect, useState } from "react";
import { ShipAlertButton } from "@/components/order/ShipAlertButton";

interface Result { orderNumber: string; customerStatus: string; paymentStatus: string; fulfillmentStatus: string; total: number; currency: string; placedAt: string; items: Array<{ title: string; size: string | null; quantity: number }>; shipments: Array<{ carrier: string | null; trackingUrl: string | null; status: string | null }> }
export function TrackOrderForm() {
  const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [hydrated, setHydrated] = useState(false); const [lookup, setLookup] = useState<{ orderNumber: string; email: string } | null>(null);
  useEffect(() => setHydrated(true), []);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); setResult(null); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/order-status", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ orderNumber: form.get("orderNumber"), email: form.get("email") }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setResult(data.order); setLookup({ orderNumber: String(form.get("orderNumber") || ""), email: String(form.get("email") || "") }); } catch (failure) { setError(failure instanceof Error ? failure.message : "Order status is unavailable."); } finally { setLoading(false); } }
  return <><form onSubmit={submit} className="mt-9 grid gap-5 sm:grid-cols-2"><div><label htmlFor="orderNumber" className="mb-2 block font-mono text-xs font-bold uppercase">Order number</label><input id="orderNumber" name="orderNumber" required autoComplete="off" placeholder="AHA-..." className="min-h-12 w-full border border-border/60 bg-void px-3 py-3 uppercase text-cream focus:border-accent focus:outline-none" /></div><div><label htmlFor="orderEmail" className="mb-2 block font-mono text-xs font-bold uppercase">Checkout email</label><input id="orderEmail" name="email" type="email" required autoComplete="email" className="min-h-12 w-full border border-border/60 bg-void px-3 py-3 text-cream focus:border-accent focus:outline-none" /></div><button disabled={!hydrated || loading} className="primary-action min-h-12 px-5 py-3 text-sm sm:col-span-2">{loading ? "Checking order..." : "Check order status"}</button></form>{error && <p role="alert" className="mt-5 border-l-2 border-error pl-4 text-sm text-error">{error}</p>}{result && <section aria-live="polite" className="mt-10 border-y border-border/40 py-7"><div className="flex flex-wrap justify-between gap-5"><div><p className="font-mono text-xs uppercase text-muted">{result.orderNumber}</p><h2 className="mt-2 font-display text-2xl font-black uppercase text-success">{result.customerStatus}</h2></div><p className="font-mono text-lg font-bold">{new Intl.NumberFormat("en-US", { style: "currency", currency: result.currency }).format(result.total / 100)}</p></div><ul className="mt-6 divide-y divide-border/40">{result.items.map((item, index) => <li key={`${item.title}-${index}`} className="flex justify-between gap-4 py-3 text-sm"><span>{item.title}<span className="block text-xs text-muted">{item.size}</span></span><span>x {item.quantity}</span></li>)}</ul>{result.fulfillmentStatus !== "shipped" && result.fulfillmentStatus !== "delivered" && result.shipments.length === 0 && lookup && <ShipAlertButton orderNumber={lookup.orderNumber} email={lookup.email} />}{result.shipments.map((shipment, index) => shipment.trackingUrl ? <a key={index} href={shipment.trackingUrl} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex min-h-11 items-center text-sm font-bold text-accent underline">Track shipment with {shipment.carrier || "carrier"}</a> : null)}</section>}</>;
}
